#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain () {
    dig +short "$1" | grep -A1 'ANSWER SECTION:'
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1"
else
    print_domain_subdomain "www.$1"
    print_domain_subdomain "lb-01.$1"
    print_domain_subdomain "web-01.$1"
    print_domain_subdomain "web-02.$1"
fi
