#!/bin/bash

# Update apt package index
apt-get update -y

# Install nginx
apt-get install nginx -y

# Check if nginx.conf already contains the desired configuration
if ! grep -q "location / {" /etc/nginx/nginx.conf; then
    # Add configuration to nginx.conf
    sed -i '/http {/a \\tserver {\n\t\tlocation / {\n\t\t\techo "Hello World!";\n\t\t}\n\t}' /etc/nginx/nginx.conf
fi

# Restart nginx
service nginx restart
