#!/usr/bin/env bash

# File: 0-custom_http_response_header

# Define server block for the first server (03-web-01)
server {
    # Listen on port 80
    listen 80;

    # Define the server name
    server_name 34.198.248.145;

    # Define the location block for handling requests
    location / {
        # Set the HTTP status code to 200
        return 200 'Hello, World!';

        # Add a content-type header
        add_header Content-Type text/plain;

        # Add the custom response header with the server name
        add_header X-Served-By "03-web-01";
    }
}

# Define server block for the second server (03-web-02)
server {
    # Listen on port 80
    listen 80;

    # Define the server name
    server_name 54.89.38.100;

    # Define the location block for handling requests
    location / {
        # Set the HTTP status code to 200
        return 200 'Hello, World!';

        # Add a content-type header
        add_header Content-Type text/plain;

        # Add the custom response header with the server name
        add_header X-Served-By "03-web-02";
    }
}

