#!/usr/bin/env bash
# Configures Nginx server to listen on port 80.

# creates a symbolic

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
#terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
