#!/usr/bin/env bash
# Stop Nginx service
service nginx stop

# Change ownership of Nginx directories
chown -R nginx:nginx /var/log/nginx /var/lib/nginx

# Change Nginx user in the configuration
sed -i 's/^user\s\+.*$/user nginx;/' /etc/nginx/nginx.conf

# Modify the default site configuration to listen on port 8080
sed -i 's/listen\s\+80;/listen 8080;/g' /etc/nginx/sites-available/default

# Ensure Nginx is listening on all active IPs
sed -i '/listen 8080;/a listen [::]:8080;' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start

# Check if Nginx is running as nginx user and listening on port 8080
if ps auxff | grep "ngin[x]" | grep -q "nginx: master process"; then
    echo "Nginx is running as the nginx user."
else
    echo "Nginx is not running as the nginx user."
fi

nc -z 0 8080
